# This is a basic workflow to help you get started with Actions

name: Deploy to DevDesk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Github hosted runner - TODO: Look at migrating to self-hosted - pro/cons
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Log the start
        run: printf "[INFO] Staring GitHub Action custom build job\n" # TODO: - check if you can call a script

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          printf "[INFO] Add other actions to build\n"
          printf "[INFO] Deploy your project\n"
  deploy: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 # Get your code from the repository
  
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.9.0 # Action to set up SSH agent
          with:
            ssh-private-key: ${{ secrets.DEV_DSK_DEPLOY_KEYS }}
            
        - name: Setup SSH Directory with TODO of adding to known hosts.
          run: |
            mkdir -p ~/.ssh
            chmod 0700 ~/.ssh
            echo "${{ secrets.DEV_DSK_DEPLOY_KEYS }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            printf "We did it Patrick, we saved the city\n"
